server:
  port: 8083
spring:
  application:
    name: lingmeng-manager
  servlet:
    multipart:
      max-file-size: 5MB  #限制上传文件大小
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lingmeng?serverTimezone=GMT%2B8
    username: root
    password: huangtao123456
    hikari:
      maximum-pool-size: 30 #最大连接数目
      minimum-idle: 10  #最大空闲数目
  mail:
    username: huangtaosta@163.com
    password: EFFNOBWEJEBQFVAU
    host: smtp.163.com
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 994 #465或者994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  rabbitmq: #配置mq
    username: /lingmeng
    password: 123456
    host: 192.168.189.129
  redis:
    host: 192.168.189.129
mybatis-plus:                #配置mybatis的映射包
  mapper-locations: classpath*:com/lingmeng/dao/**/xml/*Mapper.xml
  typeAliasesPackage: com.lingmeng.model.*.model
  configuration:
    map-underscore-to-camel-case: true  #开启user_name 对应userName驼峰命名法
    cache-enabled: true
jwt:
  secret: lingmengSecret
  pubKeyPath: D:\\tem_key\\rsa.pub
  priKeyPath: D:\\tem_key\\rsa.pri
  expire: 30
  cookieName: LM_TOKEN
  cookieMaxAge: 30
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true #表示不使用主机名来定义 而是使用IP
    ip-address: 127.0.0.1  #ip
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 2 #5s发送一次心跳
    lease-expiration-duration-in-seconds: 20 #10s不发送就过期
ribbon:
    listOfServers: http://localhost:8090
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.56.101:22122
logging:
  level:
    com.lingmeng.dao: debug