server:
  port: 10010
spring:
  application:
    name: api-gateway
  redis:
    host: 192.168.189.134
eureka:
  client:
    service-url:
      defaultZone: http://192.168.189.134:10086/eureka #注册到eureka上的端口地址
    registry-fetch-interval-seconds: 5 #定期5s去拉取服务上的注册信息
  instance:
    prefer-ip-address: true #表示不使用主机名来定义 而是使用IP
    ip-address: 192.168.189.134  #ip
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5 #5s发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10s不发送就过期
zuul:
  prefix: /api #前缀
  retryable: true #网关重试开关
  add-host-header: true
  sensitive-headers:       #将敏感头设置为null
  #下面添加路由规则
  routes:
    #    lingmeng-goods-service: /goods/**       #商品服务
    #    lingmeng-auth-service-improve: /auth/** #认证服务
    #    lingmeng-user-service: /user/**         #用户服务
    #    lingmeng-sms-service: /sms/**           #发送邮箱服务
    lingmeng-manager: /manager/**
jwt:
  secret: lingmengSecret
  pubKeyPath: D:\\tem_key\\rsa.pub
  priKeyPath: D:\\tem_key\\rsa.pri
  expire: 30
  cookieName: LM_TOKEN
  cookieMaxAge: 30
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
filter:
  allowPaths:
    - /api/auth           #目前知识在白名单中配置一个路由
    - /api/user/register  #用户注册放行,不拦截
    - /api/user/sendEmailCode #发送email不拦截
    - /api/goods             #商品不拦截
    - /api/manager             #商品不拦截



