server:
  port: 8082
spring:
  application:
    name: lingmeng-goods-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lingmeng?serverTimezone=GMT%2B8
    username: root
    password: huangtao123456
    hikari:
      maximum-pool-size: 30 #最大连接数目
      minimum-idle: 10  #最大空闲数目

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true #表示不使用主机名来定义 而是使用IP
    ip-address: 127.0.0.1  #ip
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5 #5s发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10s不发送就过期
logging:
  level:
    com.lingmeng.goods.mapper: debug