server:
  port: 8000
spring:
  application:
    name: lingmeng-auth-service-improve
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true #表示不使用主机名来定义 而是使用IP
    ip-address: 127.0.0.1  #ip
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5 #5s发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10s不发送就过期
jwt:
  secret: lingmengSecret
  pubKeyPath: D:\\tem_key\\rsa.pub
  priKeyPath: D:\\tem_key\\rsa.pri
  expire: 30
  cookieName: LM_TOKEN
  cookieMaxAge: 30